brew 'git'
brew 'gitup'
brew 'stow'
brew 'ag'
brew 'ctags'
brew 'python3'
brew 'httpie'
brew 'thefuck'
brew 'pipenv'
brew 'legit'
brew 'jrnl'
brew 'hub'
brew 'rust', args: ['with-racer']
brew 'go'
brew 'mono'
brew 'node'
brew 'yarn'
brew 'ruby'
brew 'fasd'
brew 'neovim'
brew 'macvim', args: ['with-luajit', 'with-python3', 'with-override-system-vim']

cask 'alfred'
cask 'docker'
cask 'dropbox'
cask 'gpg-suite'
cask 'iterm2'
cask 'keybase'
cask 'visual-studio-code'

tap 'caskroom/cask'
tap 'caskroom/fonts'
cask 'font-hack'

tap 'd12frosted/emacs-plus'
brew 'emacs-plus'
