[".tmux"]
    type = "git-repo"
    url = "https://github.com/gpakosz/.tmux.git"
[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
