#!/bin/sh
if [ -d $HOME/.zprezto/.git ]; then
  echo "Updating Prezto...\c"
  ( cd $HOME/.zprezto && git pull && git submodule update --init --recursive ) &> /dev/null
  echo "done!"
else
  if [ ! -d $HOME/.zprezto ]; then
    echo "Installing Prezto...\c"
    ( git clone https://github.com/sorin-ionescu/prezto.git $HOME/.zprezto && ( cd $HOME/.zprezto && git submodule update --init --recursive ) ) &> /dev/null
    echo "done!"
  fi
fi

if [ -d $HOME/.config/base16-shell/.git ]; then
  echo "Removing Base16 Shell...\c"
  ( rm -rf $HOME/.config/base16-shell ) &> /dev/null
  echo "done!"
fi

if [ ! -d $HOME/.vim/bundle/repos/github.com/Shougo/dein.vim ]; then
  echo "Uninstalling NeoBundle...\c"
  rm -rf $HOME/.vim/bundle
  echo "done!"
  echo "Installing Dein.vim...\c"
  mkdir -p $HOME/.vim/bundle/repos/github.com/Shougo
  ( git clone https://github.com/Shougo/dein.vim $HOME/.vim/bundle/repos/github.com/Shougo/dein.vim ) &> /dev/null
  echo "done!"
fi

echo "Updating Vim plugins...\c"
vim -u $HOME/.vimrc.bundles -e -s +NeoBundleInstall! +NeoBundleClean! +qa
echo "done!"

if command -v apm >/dev/null 2>&1 && [ -f $HOME/.atom/packages.txt ]; then
  echo "Updating Atom packages...\c"
  apm install --packages-file $HOME/.atom/packages.txt &> /dev/null
  echo "done!"
fi
