# frozen_string_literal: true

tap 'AdoptOpenJDK/openjdk'
tap 'd12frosted/emacs-plus'
tap 'fabianishere/personal'
tap 'heroku/brew'
tap 'homebrew/cask-fonts'
tap 'kryptco/tap'

brew 'ag'
brew 'asdf'
brew 'automake'
brew 'bat'
brew 'cocoapods'
brew 'crystal'
brew 'ctags'
brew 'd12frosted/emacs-plus/emacs-plus'
brew 'exa'
brew 'fabianishere/personal/pam_reattach'
brew 'fasd'
brew 'fd'
brew 'fish'
brew 'fnm'
brew 'fonttools'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'git-crypt'
brew 'git-delta'
brew 'gnu-sed'
brew 'go'
brew 'helm'
brew 'heroku/brew/heroku'
brew 'httpie'
brew 'hub'
brew 'jenv'
brew 'jq'
brew 'kryptco/tap/kr'
brew 'kubectl'
brew 'ledger'
brew 'legit'
brew 'm-cli'
brew 'macvim'
brew 'mas'
brew 'mkcert'
brew 'neovim'
brew 'node'
brew 'overmind'
brew 'pipenv'
brew 'pyenv'
brew 'python'
brew 'rbenv'
brew 'redis', restart_service: :changed
brew 'rg'
brew 'ruby'
brew 'rustup'
brew 'starship'
brew 'stow'
brew 'thefuck'
brew 'tmux'
brew 'tmuxinator-completion'
brew 'travis'
brew 'watch'
brew 'yarn'
brew 'yq'

cask '1password'
cask '1password-cli'
cask 'AdoptOpenJDK/openjdk/adoptopenjdk15-openj9'
cask 'alacritty'
cask 'alfred'
cask 'alt-tab'
cask 'balenaetcher'
cask 'chromedriver'
cask 'dash'
cask 'discord'
cask 'docker'
cask 'dotnet-sdk'
cask 'dropbox'
cask 'figma'
cask 'firefox'
cask 'gitup'
cask 'gnucash'
cask 'google-chrome'
cask 'gpg-suite'
cask 'homebrew/cask-fonts/font-hack-nerd-font'
cask 'homebrew/cask-fonts/font-jetbrains-mono-nerd-font'
cask 'imageoptim'
cask 'keybase'
cask 'metabase'
cask 'microsoft-edge'
cask 'minecraft'
cask 'nordvpn'
cask 'notion'
cask 'opera'
cask 'postgres'
cask 'responsively'
cask 'rocket'
cask 'slack'
cask 'steam'
cask 'twitch'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'visual-studio-code'
cask 'vivaldi'
cask 'xscreensaver'
cask 'zoomus'

mas 'AdGuard for Safari', id: 1_440_147_259
mas 'Grammarly for Safari', id: 1_462_114_288
mas 'Jira Cloud by Atlassian', id: 1_475_897_096
mas 'Krypton', id: 1_512_484_779
mas 'Name Mangler 3', id: 603_637_384
mas 'Pixelmator', id: 407_963_104
mas 'Spark', id: 1_176_895_641
mas 'Todoist', id: 585_829_637
mas 'Xcode', id: 497_799_835
mas 'Yoink', id: 457_622_435
