#!/bin/bash

cd $HOME
platform=`uname -a`

echo "= Dotfiles Setup ="

echo "== Initialize Submodules =="
yadm submodule update --recursive --init

if echo $platform | grep -q Darwin; then
  echo "== macOS Installation =="

  if ! command -v brew >/dev/null 2>&1; then
    echo "=== Installing Homebrew ==="
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  [[ -f "$HOME/.Brewfile" ]] && brew bundle --global
  [[ -f /etc/zshenv ]] && sudo mv /etc/zshenv /etc/zshrc
elif echo $platform | grep -q Linux; then
  echo "== Ubuntu Installation =="
  sudo apt-get install build-essential zsh vim-nox luajit python3 python3-dev python3-pip silversearcher-ag stow exuberant-ctags
  sudo -H pip3 install thefuck
fi

[[ $SHELL == "/bin/zsh" ]] || chsh -s /bin/zsh
